Fixed this error :- ../../../../../source/thirdparty/epd/pervasive/src/services/EPD_tc/EPD_hw_timer.c:55:31: fatal error: conf_EPD_hw_timer.h: No such file or directory  #include "conf_EPD_hw_timer.h"
1, module_cofig created and file "conf_EPD_hw_timer.h" moved to D:\Arunkarkki\Atmel\Stash\ASF\thirdparty\epd\pervasive\src\services\EPD_tc\module_config
2, asf.xml has updated for the above change